### PR TITLE
New pull request from Lucky

### PR DESCRIPTION
**Pull request by windragon0910**
I create a new HTML file.

### CODE REVIEW

**Comment by windragon0910** [comment]
animation style added

**Comment by zero10xy** [comment]
hi @windragon0910 

make sure to link your result here:
public/Challenges/Challenge-number-1/submits/submits.html
not here:
public/Challenges/Challenge-number-1/Challenge-number-1.html

**Comment by windragon0910** [comment]
Link the result in submits.html again.

**Comment by zero10xy** [comment]
ok never mind i will update it

**Pull request merged**
